language: node_js

# these are the only branches we should build on when we push to a branch
branches:
  only:
    - master

services:
  - docker

install: skip

scrip:
  - docker build -f client/Dockerfile.dev -t react-test client
  - docker run -e "CI=true" react-test npm test
  - docker build -t jerryudemy/pro-client client/
  - docker build -t jerryudemy/pro-worker worker/
  - docker build -t jerryudemy/pro-server server/
  - docker build -t jerryudemy/pro-nginx nginx/
  - docker push jerryudemy/pro-client
  - docker push jerryudemy/pro-worker
  - docker push jerryudemy/pro-server
  - docker push jerryudemy/pro-nginx