language: node_js

# these are the only branches we should build on when we push to a branch
branches:
  only:
    - master

services:
  - docker

install: skip

scrip:
  - docker build -f client/Dockerfile.dev -t react-test client
  - docker run -e "CI=true" react-test npm test
  - docker build -t pro-client client/
  - docker build -t pro-worker worker/
  - docker build -t pro-server server/
  - docker build -t pro-nginx nginx/