services:

  load_balancer:
    image: nginx:1.26.2
    volumes:
      - ./nginx-config:/etc/nginx/conf.d/default.conf
    ports:
      - '8000:80'

  express:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/server/node_modules
      - ./server:/app/server
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PGHOST: database
      PGUSER: postgres
      PGPASSWORD: jerrydocker


  react:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/client/node_modules
      - ./client:/app/client
    environment:
      SERVER_HOST: express
      SERVER_PORT: 5000

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - /app/worker/node_modules
      - ./worker:/app/worker


  redis:
    image: redis:7.2.3

  database:
    image: postgres:15-alpine3.19
    environment:
      POSTGRES_PASSWORD: jerrydocker