FROM node:20-alpine

WORKDIR /app/client

COPY client/package.json ./package.json
COPY client/package-lock.json ./package-lock.json

RUN npm install

WORKDIR /app/server

COPY server/package.json .
RUN npm install

WORKDIR /app/worker

COPY worker/package.json .
RUN npm install

# now add source code
WORKDIR /app/client
COPY client/ .

WORKDIR /app/server
COPY server/ .

WORKDIR /app/worker
COPY worker/ .

# WORKDIR /app/server
# CMD ["npm", "start"]

# WORKDIR /app
# CMD ["bash", "-c", '"cd "']