services:

  load_balancer:
    image: jerryudemy/pro-nginx
    ports:
      - '80:80'

  express:
    image: jerryudemy/pro-server
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PGHOST: database
      PGUSER: postgres
      PGPASSWORD: prodocker

  react:
    image: jerryudemy/pro-client
    environment:
      SERVER_HOST: express
      SERVER_PORT: 5000
      
  worker:
    image: jerryudemy/pro-worker
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis:7.2.3

  database:
    image: postgres:15-alpine3.19
    environment:
      POSTGRES_PASSWORD: prodocker